args <- commandArgs(trailingOnly=TRUE)
root <- normalizePath(args[1],winslash="/",mustWork=TRUE)
source(file.path(root,".agents/skills/geo-single-cell-loader/scripts/seurat_common.R"))
m <- read_manifest(file.path(root,"data/GSE999999999/.workflow/sample_manifest.csv"),root)
object <- readRDS(file.path(root,"data/GSE999999999/seurat_raw.rds"))
validate_object(object,m)
stopifnot(inherits(object,"Seurat"),ncol(object)==16L,nrow(object)==250L)
stopifnot(identical(rownames(object@meta.data),SeuratObject::Cells(object)))
stopifnot(all(table(object$sample)==4L),sum(object$group=="Fixture_A")==4L,sum(object$group=="Fixture_B")==12L)
stopifnot(all(startsWith(colnames(object),paste0(object$sample,"_"))))
for(field in required_fields) stopifnot(identical(unname(as.character(object[[field]][,1])),unname(m[[field]][match(object$sample,m$sample)])))
cat("PASS: independent RDS read; dimensions, exact metadata, groups, prefix and cell order\n")
